baseURL = 'https://azaleakamellia.github.io/'
languageCode = 'en-us'
title = 'ANECDATA'
theme = 'archie'

copyright = "© Azalea Kamellia"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally
	subtitle = "Anecdotal thesis of spatial science observations."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/azaleakamellia/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/azaleakamellia/"

[[params.social]]
name = "Youtube"
icon = "youtube"
url = "https://youtube.com/@azaleakamellia/"

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Portfolio"
url = "/portfolio"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
