baseURL = 'https://azaleakamellia.github.io/'
languageCode = 'en-us'
title = 'ANECDATA'
theme = 'archie'

copyright = "© Azalea Kamellia"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "Anecdotal thesis of spatial science observations."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/azaleakamellia/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/azaleakamellia/"

[[params.social]]
name = "Youtube"
icon = "youtube"
url = "https://youtube.com/@azaleakamellia/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Portfolio"
url = "/portfolio"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5
